# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:

- task: DownloadSecureFile@1
  name: settingsxml
  inputs:
    secureFile: 'settings.xml'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/.m2"
      Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"

- task: DownloadSecureFile@1
  name: my_pattxt
  inputs:
    secureFile: 'my_pat.txt'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Force "$(my_pattxt.secureFilePath)" "${HOME}/my_pat.txt"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/.m2/repository/org/primefaces/themes/ultima/1.1"
      cat ${HOME}/my_pat.txt | az devops login
      az artifacts universal download --organization "https://dev.azure.com/Mashreq-GEO-IT/" --project "8fcba7d6-4e34-4d08-830e-2e1288619110" --scope project --feed "repo_unilever" --name "ultima" --version "1.1.0" --path "${HOME}/.m2/repository/org/primefaces/themes/ultima/1.1"

- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: '$(MAVEN_CACHE_FOLDER)'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
  displayName: Cache Maven local repo

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/work/1/s/target/autoclaims-1.0.war'
    ArtifactName: 'AutoClaims_BE'
    publishLocation: 'Container'

- task: JBossDeployer@1
  inputs:
    credsType: 'inputs'
    jbossServerUrl: '$(server_url)'
    jbossManagementUser: 'admin'
    jbossPassword: 'admin123'
    file: '/home/vsts/work/1/s/target/autoclaims-1.0.war'
    serverMode: 'standalone'